name: CI/CD Pipeline for nginx-app # Имя конвеера

on:                 # Триггер, по которому будет запускаться конвеер
  push:             # Запускает рабочий процесс по событиям push запросов
    branches: main  # Ветка куда обращаемся
    tags: 
      - '1*'

env:                             # Описание переменных
  IMAGE: slavazakariev/nginx-app # Переменная образа в Docker Hub
  RELEASE_NAME: nginx-app        # Переменная приложения в Docker Hub
  NAMESPACE: monitoring          # Переменная пространства имён в Kubernetes

jobs:                             # Задачи, которые будут выполняться в рамках конвеера
  build-and-push:                 # Тип задачи - Сборка и Публикация
    name: Build Docker image      # Имя задачи - Сборка образа
    runs-on: ubuntu-latest        # Тип виртуальной машины, на которой будет выполняться задача
    steps:                        # Шаги, которые будут выполняться в процессе
      - name: Checkout            # Имя шага
        uses: actions/checkout@v3 # Шаблон GitHub - Доступ к содержимому репозитория
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Шаблон GitHub - Доступ в Doсker Hub 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Логин в Doсker Hub
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Пароль в Doсker Hub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Шаблон GitHub - Сборка к содержимому репозитория

      - name: Extract version from commit messages
        run: |
          VERSION=$(git log -1 --pretty=format:%B)
          if [[ ! -z "$VERSION" ]]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No version found in the commit message"
            exit 1
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}

  deploy:                      # Задачи публикации, которые будут выполняться в рамках конвеера
    needs: build-and-push
    name: Deploy to Kubernetes
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/1')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Extract version from commit messages
        run: |
          VERSION=$(git log -1 --pretty=format:%B)
          if [[ ! -z "$VERSION" ]]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No version found in the commit message"
            exit 1
          fi

      - name: Replace image tag in deployment.yaml
        if: env.DEPLOY == 'false'
       
        run: |
          sed -i "s|image: slavazakariev/nginx-app:.*|image: ${{ env.IMAGE }}|" ./nginx-app/deployment.yaml
        env:
          IMAGE_TAG: slavazakariev/nginx-app:${{ env.VERSION }}
      
      - name: Create kubeconfig
        run: |
          mkdir -p $HOME/.kube/
      - name: Authenticate to Kubernetes cluster
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBE_CONFIG_DATA}" | base64 --decode > ${HOME}/.kube/config
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./nginx-app/deployment.yaml
